### PR TITLE
Add Row Pin Extra Column sample React template

### PR DESCRIPTION
**Pull request by skrustev**

### CODE REVIEW

File: code-gen-library/WebGridRowPinCellTemplate/React.tsx [hunk 1]
```diff
@@ -0,0 +1,22 @@
+//begin imports
+import { IgrCellTemplateContext } from 'igniteui-react-grids';
+//end imports
+
+export class WebGridRowPinCellTemplate {
+//begin template
+//begin content
+public webGridRowPinCellTemplate = (e: {dataContext: IgrCellTemplateContext}) => {
+    const index = e.dataContext.cell.row.index;
```
Comment (dkamburov) [inline code-gen-library/WebGridRowPinCellTemplate/React.tsx:9]: Property 'row' does not exist on type 'IgrCellType'.ts

image

Comment (dkamburov) [reply code-gen-library/WebGridRowPinCellTemplate/React.tsx:9]: @skrustev row seems to be missing

Comment (gmurray81) [reply code-gen-library/WebGridRowPinCellTemplate/React.tsx:9]: I think this should be fixed in latest version

Comment (MayaKirova) [reply code-gen-library/WebGridRowPinCellTemplate/React.tsx:9]: @dkamburov Yes. It should be fixed but will need a new build since it was merged yesterday: https://infragistics.visualstudio.com/NetAdvantage/_git/dev-tools/pullrequest/10616

Comment (dkamburov) [reply code-gen-library/WebGridRowPinCellTemplate/React.tsx:9]: It's working fine in 18.3.0-beta.5

**Review by dkamburov — APPROVED** [review]
